# Generated by Django 5.2.6 on 2026-06-04 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(choices=[('TRC20', 'TRC20 (Tron)'), ('BEP20', 'BEP20 (BSC)')], max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='like',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario',
        ),
        migrations.CreateModel(
            name='RecargaCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('txid', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('voucher', models.ImageField(upload_to='crypto/')),
                ('estado', models.CharField(default='revision', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Amistad',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
