# Generated by Django 5.2.6 on 2026-01-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0010_recarga_oculto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apuesta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado', models.CharField(max_length=10)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
